[package]
name = "curdk"
version = "0.0.1"
authors = ["Artem V. Ageev <artem.v.ageev@gmail.com>"]
license = "GPL-2"
repository = "https://github.com/theavege/curdk-rs"
description = "Rust bindings for the Curses Development Kit"
keywords = ["CDK", "curdk"]
categories = ["api-bindings", "tui"]
edition = "2024"
exclude = ["examples"]

[dependencies]
curdk-sys = { path = "../curdk-sys", version = "=0.0.1"}
